### ISSUE TITLE
Dragging Actor to Map "Lags"

### ISSUE THREAD

**Issue by Nargath** [ElfFriend-DnD/foundryvtt-tokenOwnerSelectionTweak#3]
Foundry: 0.7.3

When dragging an actor to a map, the token does not appear on the map until hitting F5.

It also generates this error in the logs:
![image](https://user-images.githubusercontent.com/5538979/95015979-cfbe8800-069b-11eb-956d-f9cb95825842.png)

Which when expanded in the debug is this line:
![image](https://user-images.githubusercontent.com/5538979/95015997-f2e93780-069b-11eb-965b-1ca464bebae6.png)

Was tested on no modules loaded except for this one, and the tokens don't show until refresh.
Removing just this single module enabled the tokens to show instantly.

**Comment by akrigline** [comment]
I suspect 073 changed the method I'm overriding. Will probably have to use `const is07x = !isNewerVersion("0.7.0", game.data.version);` to check foundry versions somewhere.

**Comment by akrigline** [comment]
Turns out this module isn't necessary at all in 0.7.x

> When a player controls a Token that does not have vision itself, their vision will now be unified with other observed tokens. This will work better for summons or familiars where the user does not benefit from the Token's perspective.

As of [0.7.1](https://foundryvtt.com/releases/0.7.1) 🥳 

Going to fix it so that this module does nothing if installed in 0.7.1+

**Comment by akrigline** [comment]
Resovled in 0.2.0.
